### ISSUE TITLE
Uniform names changed

### ISSUE THREAD

**Issue by Vectron** [mellinoe/veldrid-spirv#8]
in version 1.0.12 the names of the uniforms get changed from the original code.
the source uniform definition:
`#version 450
layout(set = 0, binding = 2) uniform World
{
    mat4 field_World;
};`

after crosscompile in 1.0.12:
`#version 330
layout(std140) uniform vdspv_0_2
{
    mat4 field_World;
} _13;`

after crosscompile in 1.0.11:
`#version 330
layout(std140) uniform World
{
    mat4 field_World;
} _13;`

**Comment by guuskuiper** [comment]
Please fix this issue, since version 1.0.12 of this package prevents SPIR-V shaders to work under OpenGL.

**Comment by seanspicer** [comment]
Eric, I think this is the same bug I'm seeing with OpenGL in NexSceneGraph as well:

https://github.com/seanspicer/nexscenegraph

**Comment by feliwir** [comment]
This was fixed in `1.0.13`

**Comment by jeske** [comment]
This bug is still present in head of tree ppy/veldrid-spirv and veldrid/veldrid-spirv as of today. I've submitted the pull request above to fix it.
